// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjpwuunjdfjvdmhqssgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqcHd1dW5qZGZqdmRtaHFzc2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODE3NjcsImV4cCI6MjA3MTM1Nzc2N30.3vAip7yoLEZz2PblKbTZBRwJ6Ua3yLdhZiUa-tT6SUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});